name: standup_randomizer
description: Helps you with your daily Scrum Stand-Up by randomizing the order, provide a time-box and more
version: 1.0.0+2

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  animations: ^1.0.0+5
  http: ^0.12.1
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
