name: standup_randomizer
description: Helps you with your daily Scrum Stand-Up by randomizing the order, provide a time-box and more

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  animations: ^1.0.0+5
  http: ^0.12.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
