# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    container: cirrusci/flutter:latest
    steps:
    - uses: actions/checkout@v2

    - name: Analyze
      run: flutter analyze --no-congratulate || exit $?

    - name: Test
      run: 
        flutter test --coverage
